version: '3.8'

services:
  graylog:
    image: graylog/graylog:4.2
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin/admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9090/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    volumes:
      - ./graylog_journal:/usr/share/graylog/data/journal
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9090:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - internal

  mongo:
    image: mongo:4.2
    volumes:
      - ./mongo_data:/data/db
    networks:
      - internal
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - internal

  consul:
    image: consul:latest
    container_name: pepe-consul
    command: agent -server -client 0.0.0.0 -bootstrap -ui
    ports:
      - 8500:8500
    volumes:
      - consul-data:/consul/data
    labels:
      - "SERVICE_IGNORE=true"
    networks:
      - internal

  consul-init:
    image: consul:latest
    container_name: pepe-consul-init
    command: ["/scripts/consul-init.sh"]
    volumes:
      - ./scripts/consul:/scripts
    environment:
      CONSUL_HOST: consul
      CDN_URL: http://${HOSTNAME}:1080/static/
    depends_on:
      - consul
    labels:
      - "SERVICE_IGNORE=true"
    networks:
      - internal

  consul-template:
    image: hashicorp/consul-template:alpine
    container_name: "consul-template-dev"
    hostname: consul-template
    networks:
      - internal
    volumes:
      - "./consul-template.hcl:/data/consul-template.hcl:ro"
      - "./src/config:/config"
    command: consul-template -config /data/consul-template.hcl

  registrator:
    image: gliderlabs/registrator
    container_name: pepe-registrator
    entrypoint: /bin/registrator -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
    networks:
      - internal

  vault:
    image: vault:latest
    container_name: pepe-vault
    ports:
      - 8200:8200
    volumes:
      - ./etc/vault:/vault/config
      - ./scripts/vault:/scripts
    command: server
    depends_on:
      - consul
    labels:
      - "SERVICE_8200_NAME=vault"
      - "SERVICE_8200_TAGS=develop"
    networks:
      - internal

  vault-init:
    image: vault:latest
    command: ["/scripts/vault-init.sh", "--init"]
    container_name: pepe-vault-init
    volumes:
      - ./scripts/vault:/scripts
    environment:
      VAULT_HOST: vault
    depends_on:
      - vault
    labels:
      - "SERVICE_IGNORE=true"
    networks:
      - internal

volumes:
  consul-data:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local

networks:
  internal:
    driver: bridge
    name: pepe-network-test
